### PR TITLE
Cleaned Up travis.yml

### PR DESCRIPTION
**Pull request by rdittrich97**
Hopefully this works

### CODE REVIEW

**Comment by y2s82** [comment]
Hmmm our build is failing.  It can no longer make an implicit conversion from char to std::string, it seems.  that's odd.

**Comment by rdittrich97** [comment]
Probably a new addition since I upgraded g++-5 to g++-8. It should be a trivial fix

**Comment by y2s82** [comment]
Do you also not need sudo anymore?

**Comment by rdittrich97** [comment]
For installing packages? We still use sudo to install the ones we build manually

**Comment by y2s82** [comment]
how about the apt?

**Pull request merged**
