### PR TITLE
Fix #48: correct .travis.yml - scons install, fix indenting for env

### LINKED ISSUE #48: Fixes to .travis.yml
A few things I see in your `.travis.yml` file:

* https://github.com/y2s82/goblin_camp/blob/master/.travis.yml#L17 should be `scons` vs. `scon`
* watch your tab vs. spaces https://github.com/y2s82/goblin_camp/blob/master/.travis.yml#L5

cc @rdittrich97

### PR DESCRIPTION
**Pull request by humphd**
Fixes for the things I noticed.  I also removed the `global` bit in your `env`, as I don't think you need it.

### CODE REVIEW

**Comment by humphd** [comment]
Fixed the current build failure, but it now fails with a new issue, https://askubuntu.com/questions/920866/unable-to-install-libsdl2-dev-due-to-unmet-dependencies

**Comment by humphd** [comment]
OK, I got it to build, but the build now fails with:

```
g++ -o libtcod-1.9.0-x86_64-DEBUG/src/libtcod/gui/vbox.os -c -std=c++14 -Wall -g -fvisibility=hidden -m64 -fPIC -D_REENTRANT -DLIBTCOD_EXPORTS -Ilibtcod-1.9.0-x86_64-DEBUG/src/vendor/zlib -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor/zlib -I/usr/include/SDL2 -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor /home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/libtcod/gui/vbox.cpp
g++ -o libtcod-1.9.0-x86_64-DEBUG/src/libtcod/gui/widget.os -c -std=c++14 -Wall -g -fvisibility=hidden -m64 -fPIC -D_REENTRANT -DLIBTCOD_EXPORTS -Ilibtcod-1.9.0-x86_64-DEBUG/src/vendor/zlib -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor/zlib -I/usr/include/SDL2 -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor /home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/libtcod/gui/widget.cpp
g++ -o libtcod-1.9.0-x86_64-DEBUG/src/libtcod/sdl2/gl2_display.os -c -std=c++14 -Wall -g -fvisibility=hidden -m64 -fPIC -D_REENTRANT -DLIBTCOD_EXPORTS -Ilibtcod-1.9.0-x86_64-DEBUG/src/vendor/zlib -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor/zlib -I/usr/include/SDL2 -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor /home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/libtcod/sdl2/gl2_display.cpp
g++ -o libtcod-1.9.0-x86_64-DEBUG/src/libtcod/sdl2/gl2_raii.os -c -std=c++14 -Wall -g -fvisibility=hidden -m64 -fPIC -D_REENTRANT -DLIBTCOD_EXPORTS -Ilibtcod-1.9.0-x86_64-DEBUG/src/vendor/zlib -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor/zlib -I/usr/include/SDL2 -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor /home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/libtcod/sdl2/gl2_raii.cpp
g++ -o libtcod-1.9.0-x86_64-DEBUG/src/libtcod/sdl2/gl2_renderer.os -c -std=c++14 -Wall -g -fvisibility=hidden -m64 -fPIC -D_REENTRANT -DLIBTCOD_EXPORTS -Ilibtcod-1.9.0-x86_64-DEBUG/src/vendor/zlib -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor/zlib -I/usr/include/SDL2 -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor /home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/libtcod/sdl2/gl2_renderer.cpp
g++ -o libtcod-1.9.0-x86_64-DEBUG/src/libtcod/sdl2/gl_alias.os -c -std=c++14 -Wall -g -fvisibility=hidden -m64 -fPIC -D_REENTRANT -DLIBTCOD_EXPORTS -Ilibtcod-1.9.0-x86_64-DEBUG/src/vendor/zlib -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor/zlib -I/usr/include/SDL2 -I/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/vendor /home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/libtcod/sdl2/gl_alias.cpp
/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/libtcod/sdl2/gl_alias.cpp: In static member function ‘static int tcod::sdl2::OpenGLInternalTilesetAlias_::on_sdl_event(void*, SDL_Event*)’:
/home/travis/build/y2s82/goblin_camp/libtcod-1.9.0/src/libtcod/sdl2/gl_alias.cpp:113:12: error: ‘SDL_RENDER_DEVICE_RESET’ was not declared in this scope
       case SDL_RENDER_DEVICE_RESET: // Lost all textures.
            ^
scons: *** [libtcod-1.9.0-x86_64-DEBUG/src/libtcod/sdl2/gl_alias.os] Error 1
scons: building terminated because of errors.
The command "scons develop" failed and exited with 2 during .
```

I think you can probably review my changes and take over from here, since the scope of this bug is done, and we're into something else that needs understanding of the build vs. build setup.

**Comment by y2s82** [comment]
oh this is a different bug then we encountered when we got it to build.  I wonder what we did differently. We instead ran straight into segmentation fault and fell in despair.  At least this one, we know where to look.

thank you professor.

**Comment by humphd** [comment]
I'm guessing it's some kind of version issue with the `libtcod` vs. `libsdl`.  Maybe you don't have the right mix here, or not everything is 64 bit, or...maybe something else:

http://hg.libsdl.org/SDL/rev/d7d2e69a0b08

**Comment by humphd** [comment]
Based on https://github.com/veandco/go-sdl2/blob/master/sdl/events.go#L21, I'd say that you can't use SDL vs. 1.2.  Try bumping that up to something newer?

**Comment by y2s82** [comment]
hmmm we do have libsdl2-dev installed as well.  Wonder if we can just use the version 2.

**Comment by humphd** [comment]
No, in `.travis.yml` you currently have `- sudo apt-get install -y libsdl1.2-dev libsdl-image1.2-dev`

**Comment by y2s82** [comment]
we also have libsdl2-dev on line 16.
I think we needed libsd1 for gobin camp and libsdl2 for libtcod

**Comment by rdittrich97** [comment]
Thanks @humphd, very good work. But these issues were already being worked on in the branch issue-32, but since your changes are a bit more verbose then what I had in my branch I'll close it and we'll merge yours. I think we might have to compile libsdl2 from source to fix the SDL_RENDER_DEVICE_RESET since it was implemented in 2.0.4 and the one from the ubuntu package manager is an earlier version

**Pull request merged**
